/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Pegawai extends javax.swing.JFrame {
    
    private void kosongkanForm(){
        vNip.setEditable(true);
        vNip.setText(null);
        vNama.setText(null);
        vjenisKelamin.setSelectedItem(this);
        vJabatan.setSelectedItem(this);
        vAlamat.setText(null);
    }
    private void tampilData(){
        
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("NIP");
        model.addColumn("Nama Pegawai");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Jabatan");
        model.addColumn("Alamat");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM pegawai";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});  
            }
            tabelPegawai.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Eror:" + e.getMessage());
        }
    }

    /**
     * Creates new form Karyawan
     */
    public Pegawai() {
        initComponents();
        tampilData();
        kosongkanForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vNip = new javax.swing.JTextField();
        vNama = new javax.swing.JTextField();
        vAlamat = new javax.swing.JTextField();
        vjenisKelamin = new javax.swing.JComboBox<>();
        vJabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPegawai = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Pegawai Kecamatan");
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PEGAWAI KECAMATAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 16, 270, 29));
        jLabel1.getAccessibleContext().setAccessibleName("jlabels1\n");

        jLabel2.setText("NIP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 87, -1, -1));

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 132, -1, -1));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 188, -1, -1));

        jLabel5.setText("Jabatan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 244, -1, -1));

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 292, -1, -1));
        getContentPane().add(vNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 85, 322, -1));
        getContentPane().add(vNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 129, 322, -1));
        getContentPane().add(vAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 289, 322, -1));

        vjenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        getContentPane().add(vjenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 185, 322, -1));

        vJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camat", "Sekcam", "Kasi Trantib", "Kasi Pemerintahan", "Kasi PMD", "Kasi Pelayanan Umum", "Operator", "Staff" }));
        vJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vJabatanActionPerformed(evt);
            }
        });
        getContentPane().add(vJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 241, 322, -1));

        tabelPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPegawai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 425, 656, 166));

        bTambah.setText("Tambah data");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 356, -1, -1));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 356, -1, -1));

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 356, -1, -1));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 356, -1, -1));

        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vJabatanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_bTambahActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "INSERT INTO pegawai VALUES ('"+vNip.getText()+"','"+vNama.getText()+"','"+vjenisKelamin.getSelectedItem()+"','"+vJabatan.getSelectedItem()+"','"+vAlamat.getText()+"')";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pstm =conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Data anda berhasil disimpan..");
            tampilData();
            kosongkanForm();
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tabelPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPegawaiMouseClicked
        // TODO add your handling code here:
        int baris = tabelPegawai.rowAtPoint(evt.getPoint());
        String nip = tabelPegawai.getValueAt(baris,1).toString();
        vNip.setText(nip);
        String nama = tabelPegawai.getValueAt(baris,2).toString();
        vNama.setText(nama);
        String jk = tabelPegawai.getValueAt(baris,3).toString();
        vjenisKelamin.setSelectedItem(jk);
        String jabatan = tabelPegawai.getValueAt(baris,4).toString();
        vJabatan.setSelectedItem(jabatan);
        String alm = tabelPegawai.getValueAt(baris,5).toString();
        vAlamat.setText(alm);
        
    }//GEN-LAST:event_tabelPegawaiMouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE pegawai SET nip ='"+vNip.getText()+"',nama='"+vNama.getText()+"',jenisKelamin='"+vjenisKelamin.getSelectedItem()+"',jabatan='"+vJabatan.getSelectedItem()+"',alamat='"+vAlamat.getText()+"' WHERE nip = '"+vNip.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pstm =conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Edit data berhasil disimpan..");
            
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        tampilData();
        kosongkanForm();
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        try{
        String sql ="DELETE FROM pegawai WHERE nip='"+vNip.getText()+"'";
        java.sql.Connection conn=(Connection)config.configDB();
        java.sql.PreparedStatement pstm =conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null,"Hapus data berhasil disimpan..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        tampilData();
        kosongkanForm();
                
    }//GEN-LAST:event_bHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPegawai;
    private javax.swing.JTextField vAlamat;
    private javax.swing.JComboBox<String> vJabatan;
    private javax.swing.JTextField vNama;
    private javax.swing.JTextField vNip;
    private javax.swing.JComboBox<String> vjenisKelamin;
    // End of variables declaration//GEN-END:variables
}
